title: Mat's usefull stuff project # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi,<br>
  My name is Mat and I'm an IT Guy<br>
  I like technology and fixing things.<br>
  Preferably while using some tech to do that :)
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-171539564-1 # your Google Analytics tracking ID here
